# Generated by Django 5.1 on 2024-09-11 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commercial', '0002_products_delete_userinfo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='image',
            field=models.TextField(max_length=255),
        ),
    ]
