# Generated by Django 5.1 on 2024-09-12 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commercial', '0005_product'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(default=None, max_length=50)),
                ('last_name', models.CharField(default=None, max_length=50)),
                ('DOB', models.DateField()),
                ('gender', models.CharField(default=None, max_length=10)),
                ('address', models.TextField()),
                ('phone', models.CharField(max_length=15)),
                ('package', models.CharField(max_length=100)),
            ],
        ),
    ]
