# Generated by Django 5.1 on 2024-09-12 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commercial', '0009_alter_userprofile_dob'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='gender',
            field=models.CharField(blank=True, default=None, max_length=10, null=True),
        ),
    ]
