# Generated by Django 5.1.1 on 2024-10-01 01:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commercial', '0012_vendorprofile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vendorprofile',
            name='seller_profile',
        ),
        migrations.AddField(
            model_name='vendorprofile',
            name='DOB',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='vendorprofile',
            name='address',
            field=models.TextField(default='Not specified'),
        ),
        migrations.AddField(
            model_name='vendorprofile',
            name='first_name',
            field=models.CharField(default='Not specified', max_length=50),
        ),
        migrations.AddField(
            model_name='vendorprofile',
            name='gender',
            field=models.CharField(blank=True, default=None, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='vendorprofile',
            name='last_name',
            field=models.CharField(default='Not specified', max_length=50),
        ),
        migrations.AddField(
            model_name='vendorprofile',
            name='package',
            field=models.CharField(default='Not specified', max_length=100),
        ),
        migrations.AddField(
            model_name='vendorprofile',
            name='phone',
            field=models.CharField(default='Not specified', max_length=15),
        ),
        migrations.AlterField(
            model_name='vendorprofile',
            name='WA_link',
            field=models.URLField(default='Not specified'),
        ),
        migrations.AlterField(
            model_name='vendorprofile',
            name='brand_name',
            field=models.CharField(default='Not specified', max_length=255),
        ),
        migrations.DeleteModel(
            name='SellerProfile',
        ),
    ]
