# Generated by Django 5.1.1 on 2024-10-01 01:50

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('commercial', '0014_userproile'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UserProile',
            new_name='UserProfile',
        ),
    ]
