# Generated by Django 5.1.1 on 2024-10-01 23:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('commercial', '0017_userprofile_location'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vendorprofile',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='vendorprofile',
            name='last_name',
        ),
    ]
