# Generated by Django 5.1.1 on 2024-10-03 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commercial', '0018_remove_vendorprofile_first_name_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vendorprofile',
            old_name='profile_picture',
            new_name='brand_picture',
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='profile_picture',
            field=models.ImageField(blank=True, default='default user.png', null=True, upload_to='profile_pictures/'),
        ),
    ]
