# Generated by Django 5.1.1 on 2024-10-03 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commercial', '0019_rename_profile_picture_vendorprofile_brand_picture_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='profile_picture',
            field=models.ImageField(blank=True, default='images/default user.png', null=True, upload_to='profile_pictures/'),
        ),
    ]
