# Generated by Django 5.1.1 on 2024-10-04 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commercial', '0021_alter_userprofile_profile_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vendorprofile',
            name='brand_picture',
            field=models.ImageField(blank=True, default='brand_images/default.jpg', null=True, upload_to='brand_images/'),
        ),
    ]
