# Generated by Django 5.1.1 on 2024-10-04 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commercial', '0022_alter_vendorprofile_brand_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vendorprofile',
            name='WA_link',
            field=models.URLField(default=None),
        ),
        migrations.AlterField(
            model_name='vendorprofile',
            name='address',
            field=models.TextField(default=None),
        ),
        migrations.AlterField(
            model_name='vendorprofile',
            name='brand_name',
            field=models.CharField(default=None, max_length=255),
        ),
        migrations.AlterField(
            model_name='vendorprofile',
            name='package',
            field=models.CharField(default=None, max_length=100),
        ),
        migrations.AlterField(
            model_name='vendorprofile',
            name='phone',
            field=models.CharField(default=None, max_length=15),
        ),
    ]
