# Generated by Django 5.1.1 on 2024-10-04 22:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commercial', '0023_alter_vendorprofile_wa_link_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vendorprofile',
            name='WA_link',
            field=models.URLField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='vendorprofile',
            name='address',
            field=models.TextField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='vendorprofile',
            name='brand_name',
            field=models.CharField(blank=True, default=None, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='vendorprofile',
            name='package',
            field=models.CharField(blank=True, default=None, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='vendorprofile',
            name='phone',
            field=models.CharField(blank=True, default=None, max_length=15, null=True),
        ),
    ]
