# Generated by Django 5.1.1 on 2024-10-05 01:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commercial', '0026_alter_vendorprofile_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='email',
            field=models.EmailField(default='Not specified', max_length=255),
        ),
    ]
