# Generated by Django 5.1.1 on 2024-10-05 04:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commercial', '0028_alter_userprofile_email_alter_userprofile_first_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vendorprofile',
            name='brand_picture',
            field=models.ImageField(blank=True, default='brand_images/default.png', null=True, upload_to='brand_images/'),
        ),
    ]
