# Generated by Django 5.1.1 on 2024-10-05 04:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commercial', '0029_alter_vendorprofile_brand_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='email',
            field=models.EmailField(blank=True, default='Not specified', max_length=255, null=True),
        ),
    ]
