# Generated by Django 5.1.1 on 2024-10-07 22:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commercial', '0033_product_image1_product_image2_product_image3_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='stock',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
