# Generated by Django 5.1.1 on 2024-10-30 01:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commercial', '0035_alter_product_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=13, null=True),
        ),
    ]
